### ISSUE TITLE
Cannot get it

### ISSUE THREAD

**Issue by BoSong-Unity** [sajari/sdk-go#53]
go get -u code.sajari.com/sdk-go
go: finding code.sajari.com/sdk-go latest
go: downloading code.sajari.com/sdk-go v0.0.0-20210415013125-3d513aed759b
go: extracting code.sajari.com/sdk-go v0.0.0-20210415013125-3d513aed759b
go get: code.sajari.com/sdk-go@v0.0.0-20210415013125-3d513aed759b requires
        code.sajari.com/protogen-go@v0.0.0-20200920230145-133a858bb8ab: invalid version: git fetch -f https://review.sajari.com/a/protogen-go refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /mnt/c/Users/user/go/pkg/mod/cache/vcs/54d408c5905f83fd98f9ee664815c3ba0fbd64f3377bfe487a45e8c6cec225a7: exit
 status 128:
        fatal: could not read Username for 'https://review.sajari.com': terminal prompts disabled

**Comment by jonathaningram** [comment]
This looks to be working as expected. If you're still having issues please open a new issue. Thanks for the report.

```
% cd /tmp
% go get -u code.sajari.com/sdk-go
go: downloading code.sajari.com/sdk-go v0.0.0-20211220063040-470287d00ff5
go: downloading google.golang.org/grpc v1.43.0
go: downloading code.sajari.com/protogen-go v0.0.0-20210520073656-e34cafd11806
go: downloading golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8
go: downloading golang.org/x/net v0.0.0-20211216030914-fe4d6282115f
go: downloading google.golang.org/genproto v0.0.0-20211223182754-3ac035c7e7cb
go: downloading golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
```
